### ISSUE TITLE
Cannot get the user details once the registration process is complete

### ISSUE THREAD

**Issue by tharakabimal** [tharakabimal/blog-app#1]
I'm trying to build a custom user registration system. I have used **accounts-base** , **accounts-password** packages to register the users. 

What I have written in **[user.js](https://github.com/tharakabimal/blog-app/blob/master/client/modules/users/actions/users.js)** action is as follows

    Accounts.createUser({
			email: username,
			password: password
    });

Once the user is registered I'm trying to get the email address to display on my [header](https://github.com/tharakabimal/blog-app/blob/master/client/modules/users/components/login_header.jsx).

Below screenshot shows what I get in the user object when I log it to the console. 

![console_log](https://cloud.githubusercontent.com/assets/3351988/14560086/f0def05c-032a-11e6-8c40-6ac630089901.jpeg)

I'm new to react and meteor, it would be great if you could tell me what I'm doing wrong here. Thanks

**Comment by tharakabimal** [comment]
I made a change to the  **LoginHeader** component. Added **user.user.emails[0].address**. What's weired about it is that it worked for a while and all of a sudden it started giving me the error **Uncaught TypeError: Cannot read property 'emails' of undefined**. I am definitely doing something wrong, just can't figure out what it is.

    const LoginHeader = (user) => (
	<div>		
		<p className="navbar-text navbar-right">
			{user ? user.user.emails[0].address : <LoginRegister />}
		</p>		
	</div>
    );

**Comment by sungwoncho** [comment]
Sometimes it will work but sometimes it won't. `Meteor.user()` will not always return  the current user if called too soon (see [here](https://github.com/tharakabimal/blog-app/blob/master/client/modules/users/containers/login_header.js#L7)). You should not assume that the data is available.

What you need is something like

if (Meteor.subscribe('currentUser').ready()) {
  let user = Meteor.user();
  onData(null, {user});
}

I actually solved this problem here: https://github.com/vymio/vym/blob/aaa7b97786170ae0a5cad2229e4370744850e261/client/modules/core/containers/header.js

**Comment by tharakabimal** [comment]
Thanks @sungwoncho .

**Comment by sungwoncho** [comment]
https://talk.mantrajs.com/ is a good place to ask questions related to Mantra. Also I am making an app using Mantra and it is open source. You can have a look at https://github.com/vymio/vym if you want to see real life app with Mantra. :)

**Comment by tharakabimal** [comment]
Awesome, didn't know about Mantra Talk. Thank you so very much.
